# Generated by Django 5.2.4 on 2025-07-23 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug_products_slug_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoVariant',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='products.colovariant'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='products.sizevariant'),
        ),
    ]
