# Generated by Django 5.2.4 on 2025-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant_products_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
