# Generated by Django 5.2.4 on 2025-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_colovariant_color_alter_sizevariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='products.colovariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='products.sizevariant'),
        ),
    ]
