# Generated by Django 5.2.4 on 2025-07-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_color_alter_products_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColoVariant',
            new_name='ColorVariant',
        ),
    ]
