# Generated by Django 5.2.4 on 2025-08-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_colorvariant_color_alter_sizevariant_size'),
        ('products', '0006_rename_colovariant_colorvariant'),
    ]

    operations = [
    ]
