# Generated by Django 5.2.4 on 2025-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20250814_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
